#!/usr/bin/env python3
"""Emit the RhinoCommon preamble that makes a build STAGE scoped + idempotent.

Why this exists
---------------
The MCP execute_* wrappers were observed to run an emitted script TWICE (E1:
doubled stdout, 35 solids instead of 18). A whole-build "wipe everything and
rebuild" idempotency self-corrects the doubling but rebuilds ALL 931 solids to
fix one stage (E5/E10). This helper emits a *scoped* idempotent preamble: it
deletes ONLY the live objects whose UserString "stage" (or "part_id" prefix)
matches THIS stage, then the caller re-creates that stage's parts once. Running
the stage script twice therefore converges to exactly one copy of the stage,
and a failure in one stage never touches another stage's geometry.

It does NOT execute Rhino (no live Rhino/MCP here). It is a CODEGEN helper: it
prints a ready-to-run `#! python3` snippet to stdout that the modeling pipeline
hands to `execute_rhinoscript_python_code`. stdlib-only; 3.9-compatible; passes
`python3 -m py_compile`.

Usage
-----
    python3 stage_emit.py --stage bell_chamber
    python3 stage_emit.py --stage bell_chamber --part-ids bell_floor,bell_col_0,bell_col_1
    python3 stage_emit.py --stage bell_chamber --layer Pisa::BellChamber

The emitted snippet defines `purge_stage()` and runs it, then prints a JSON
line `{"stage": "...", "deleted": <n>}` so the caller knows the pre-state was
cleaned. The caller appends its guarded Create*/bake code AFTER this preamble,
inside the SAME execute_* call, so delete+rebuild is one atomic stage unit.

CONNECTIVITY SWEEP (conventions §13 / correction C9)
----------------------------------------------------
With `--connectivity-edges <json>` this helper ALSO emits a postamble (appended
by the caller AFTER its bake code, in the SAME execute_* call) that, per the
cheapest-high-value v2 change:
  * captures the oriented handle (obb plane + centroid) of every baked part into
    the ledger output (A2 -- world-AABB is UNSOUND for helical/rotated parts),
  * loops THIS stage's declared contact edges and measures each realized gap
    BETWEEN THE TWO LIVE SOLIDS by GUID (Brep boolean-intersection sign /
    Brep.ClosestPoint -- A1, NEVER an IR coordinate; A4 nearest-point handles
    curved/helical supports),
  * applies the per-relation-type band (A3) in-Rhino and prints ONLY the
    violations as compact JSON {"uncovered":[...],"out_of_band":[...]} (B1 --
    passing gaps never enter context).
The violations JSON is the --actual input to check_connectivity.py, which does
the offline classification + completeness enforcement. One execute call per
stage; one round-trip; the passing gaps stay server-side.
"""

import argparse
import json
import sys


# The emitted snippet. `{stage}`, `{part_ids_literal}`, `{layer_literal}` are
# filled in by render(). Everything the snippet needs is in scriptcontext.
_TEMPLATE = '''#! python3
# SCOPED IDEMPOTENT STAGE PREAMBLE -- generated by stage_emit.py
# Deletes only THIS stage's objects, then the caller re-creates them once.
# Safe to run twice (E1 double-execution self-corrects within the stage).
import scriptcontext as sc
import Rhino
import json

STAGE = {stage}
PART_IDS = {part_ids_literal}        # explicit allow-list, or None to match by stage tag
LAYER = {layer_literal}              # optional layer scope, or None

def _obj_in_stage(obj):
    """True if a live object belongs to THIS stage (delete target)."""
    a = obj.Attributes
    # 1. Strongest signal: a UserString "stage" stamped at bake time.
    if a.GetUserString("stage") == STAGE:
        return True
    # 2. Explicit part_id allow-list for this stage.
    if PART_IDS is not None:
        pid = a.GetUserString("part_id")
        if pid in PART_IDS:
            return True
    # 3. Layer scope (whole-layer stage). Compare resolved layer full path.
    if LAYER is not None:
        li = a.LayerIndex
        if 0 <= li < sc.doc.Layers.Count:
            if sc.doc.Layers[li].FullPath == LAYER:
                return True
    return False

def purge_stage():
    """Delete every live object that belongs to this stage. Returns count."""
    # Snapshot ids first; never mutate the table while enumerating it.
    doomed = [o.Id for o in sc.doc.Objects if _obj_in_stage(o)]
    n = 0
    for gid in doomed:
        if sc.doc.Objects.Delete(gid, True):   # quiet=True
            n += 1
    return n

_deleted = purge_stage()
# IMPORTANT for the create-then-find-newest shim: take the GUID snapshot for the
# newest-object diff AFTER the purge, so deleted objects never confuse the diff.
_stage_before_ids = set(o.Id for o in sc.doc.Objects)
print(json.dumps({{"stage": STAGE, "deleted": _deleted}}))
# ---- caller appends guarded Create* / bake code for this stage below ----
# Every bake in this stage MUST stamp the stage tag so a re-run can find it:
#     attr.SetUserString("stage", STAGE)
#     attr.SetUserString("part_id", part_id)
'''


# The connectivity-sweep postamble (conventions §13 / C9). Appended by the caller
# AFTER its bake code, in the SAME execute_* call. `{edges_literal}`, `{doc_tol}`
# and `{default_penetration}` are filled by render_connectivity_sweep().
#  - obb/centroid capture (A2): the oriented handle, since the world-AABB is
#    unsound for helical/rotated parts.
#  - realized_gap (A1/A4): the SIGNED gap between two LIVE solids by GUID, never
#    an IR coordinate; negative = interpenetration depth.
#  - band_for (A3): the directed per-relation-type band.
#  - prints ONLY violations (B1): {"uncovered":[...], "out_of_band":[...], "obb":{...}}.
_CONNECTIVITY_TEMPLATE = '''
# ---- CONNECTIVITY SWEEP (conventions §13 / C9) -- generated by stage_emit.py ----
# One execute call per stage; measures realized solid-to-solid gaps by GUID (A1),
# returns ONLY violations (B1). Append AFTER this stage's bake code.
import scriptcontext as sc
import Rhino
import json

_EDGES = {edges_literal}                 # this stage's declared contact edges
_DOC_TOL = {doc_tol}                      # acceptance tolerance (model units)
_DEFAULT_PEN = {default_penetration}      # default seating depth for lands_on/meets

def _live(part_id):
    """Resolve a part_id to its live object's GUID via UserString (C1). None if gone."""
    for o in sc.doc.Objects:
        if o.Attributes.GetUserString("part_id") == part_id:
            return o.Id
    return None

def _closest(src, tgt):
    """Nearest realized distance from src's edge/vertex samples onto tgt (A4).
    Samples curve edges (not only vertices) so a curved/helical rail's nearest
    arc-length point is found, not just a corner."""
    best = float("inf")
    pts = [v.Location for v in src.Vertices]
    for e in src.Edges:                              # sample along edges for curved members (A4)
        c = e.EdgeCurve
        if c is not None:
            dom = c.Domain
            for k in range(11):
                pts.append(c.PointAt(dom.ParameterAt(k / 10.0)))
    for p in pts:
        rc = tgt.ClosestPoint(p, 0.0)                # Brep.ClosestPoint -> nearest pt on realized solid
        if rc and rc[0]:
            d = rc[5]
            if d < best:
                best = d
    return best

def realized_gap(guid_a, guid_b):
    """Signed gap between two LIVE breps by GUID (A1). + = space, - = overlap depth."""
    oa = sc.doc.Objects.FindId(guid_a)
    ob = sc.doc.Objects.FindId(guid_b)
    if oa is None or ob is None:
        return None
    ba, bb = oa.Geometry, ob.Geometry
    inter = Rhino.Geometry.Brep.CreateBooleanIntersection([ba], [bb], _DOC_TOL)
    if inter and len(inter) > 0:                     # they overlap -> NEGATIVE gap (penetration)
        bx = inter[0].GetBoundingBox(True)
        return -min(bx.Max.X - bx.Min.X, bx.Max.Y - bx.Min.Y, bx.Max.Z - bx.Min.Z)
    return min(_closest(ba, bb), _closest(bb, ba))   # positive realized solid-to-solid distance

def band_for(edge):
    """Directed per-relation-type band (A3). Returns (lo, hi) or (None, None)."""
    t = edge.get("type")
    tol = edge.get("tol")
    tol = _DOC_TOL if tol is None else float(tol)
    pen = edge.get("penetration")
    pen = _DEFAULT_PEN if (pen is None or float(pen) <= 0) else float(pen)
    if t == "on_top_of":
        return (0.0, tol)
    if t == "coincident":
        return (-tol, tol)
    if t in ("lands_on", "meets", "spans", "spans_between"):
        return (-pen, tol)
    if t == "interpenetrate":
        return (-2.0, -0.5)                          # C3: union overlap must be NEGATIVE 0.5-2mm
    return (None, None)

def capture_obb(part_id):
    """Capture the A2 oriented handle (obb plane + centroid) of a baked part."""
    gid = _live(part_id)
    if gid is None:
        return None
    obj = sc.doc.Objects.FindId(gid)
    geom = obj.Geometry
    # Oriented box from a plane fit to the part's own realized vertices (so the box
    # travels with a rotated/helical member), falling back to WorldXY when a fit is
    # not possible. The world-AABB is unsound for non-axis-aligned parts (A2).
    plane = Rhino.Geometry.Plane.WorldXY
    if hasattr(geom, "Vertices"):
        rc, fitted = Rhino.Geometry.Plane.FitPlaneToPoints(
            [v.Location for v in geom.Vertices])
        if fitted is not None and fitted.IsValid:
            plane = fitted
    box = geom.GetBoundingBox(plane)
    cen = None
    vm = Rhino.Geometry.VolumeMassProperties.Compute(geom)
    if vm is not None:
        cen = [vm.Centroid.X, vm.Centroid.Y, vm.Centroid.Z]
    return {{
        "part_id": part_id,
        "obb": {{
            "origin": [plane.OriginX, plane.OriginY, plane.OriginZ],
            "x_axis": [plane.XAxis.X, plane.XAxis.Y, plane.XAxis.Z],
            "y_axis": [plane.YAxis.X, plane.YAxis.Y, plane.YAxis.Z],
            "extents": [box.Max.X - box.Min.X, box.Max.Y - box.Min.Y, box.Max.Z - box.Min.Z],
        }},
        "centroid": cen,
    }}

def sweep():
    out_of_band, uncovered, obbs = [], [], []
    seen = set()
    for e in _EDGES:
        frm, to = e.get("from"), e.get("to")
        for pid in (frm, to, e.get("to2")):
            if pid and pid not in seen:
                seen.add(pid)
                h = capture_obb(pid)                 # A2 oriented handle into the ledger
                if h is not None:
                    obbs.append(h)
        key = {{"type": e.get("type"), "from": frm, "to": to}}
        if e.get("to2"):
            key["to2"] = e.get("to2")
        ga, gb = _live(frm), _live(to)
        if ga is None or gb is None:                 # C2: endpoint deleted/never built
            uncovered.append({{"edge": key, "status": "uncovered"}})
            continue
        g = realized_gap(ga, gb)                     # A1 realized solid-to-solid by GUID
        if g is None:
            uncovered.append({{"edge": key, "status": "uncovered"}})
            continue
        lo, hi = band_for(e)
        if lo is not None and not (lo <= g <= hi):
            out_of_band.append({{"edge": key, "gap": round(g, 4), "band": [lo, hi],
                                 "measured_between": [str(ga), str(gb)],
                                 "status": "out_of_band"}})
    # B1: ONLY violations enter context; passing gaps stay server-side. obb is the
    # ledger handle the scene-graph writer persists (A2).
    print(json.dumps({{"stage": STAGE, "uncovered": uncovered,
                       "out_of_band": out_of_band, "obb": obbs}}))

sweep()
'''


def py_literal(value):
    """Render a Python literal for a str / list-of-str / None."""
    if value is None:
        return "None"
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, (list, tuple)):
        return "{" + ", ".join(repr(str(v)) for v in value) + "}"
    raise TypeError("unsupported literal: %r" % (value,))


def render(stage, part_ids, layer):
    """Return the ready-to-run stage preamble snippet as a string."""
    if not stage:
        raise ValueError("--stage is required and must be non-empty")
    return _TEMPLATE.format(
        stage=repr(str(stage)),
        part_ids_literal=py_literal(part_ids),
        layer_literal=py_literal(layer),
    )


def render_connectivity_sweep(edges, doc_tol, default_penetration):
    """Return the §13/C9 connectivity-sweep POSTAMBLE snippet (B1).

    `edges` is THIS stage's declared contact edges, each a dict
    {type, from, to, to2?, at_surface?, tol?, penetration?}. The emitted code
    measures each realized solid-to-solid gap by GUID (A1/A4), applies the
    per-relation-type band in-Rhino (A3), captures each part's obb/centroid (A2),
    and prints ONLY violations + the obb ledger as compact JSON (B1). It uses
    `STAGE` from the preamble, so it MUST be appended after render()'s output in
    the SAME execute_* call.
    """
    # Emit a PYTHON literal (repr), not json.dumps: JSON's null/true/false are not
    # valid Python names and would NameError at runtime inside the emitted script.
    return _CONNECTIVITY_TEMPLATE.format(
        edges_literal=repr(edges or []),
        doc_tol=repr(float(doc_tol)),
        default_penetration=repr(float(default_penetration)),
    )


def _load_edges(spec):
    """Load the connectivity edges from a JSON file path or inline JSON string.

    Accepts a bare list of edges, a {'edges':[...]} wrapper, or a build-plan IR /
    scene-graph wrapper ({'parts':[...]} lifts per-part relations; {'edges':[...]}
    is used directly). Only CONTACT relations are kept (logical child_of /
    symmetric_about are not measured contacts).
    """
    contact = {"on_top_of", "coincident", "lands_on", "meets",
               "interpenetrate", "spans", "spans_between"}
    try:
        data = json.loads(spec)
    except ValueError:
        with open(spec, "r", encoding="utf-8") as handle:
            data = json.load(handle)

    raw = []
    if isinstance(data, list):
        raw = data
    elif isinstance(data, dict):
        if isinstance(data.get("edges"), list):
            raw = data["edges"]
        elif isinstance(data.get("parts"), list):
            for part in data["parts"]:
                if not isinstance(part, dict):
                    continue
                pid = part.get("id")
                # Expand an array family: each relation fans out across the N
                # instances baked as part_id '<id>#<i>' so the in-Rhino _live()
                # resolves each instance's own UserString (the family id never
                # bakes as an object). An explicit relation.this overrides.
                arr = part.get("array") if isinstance(part.get("array"), dict) else None
                n = 1
                if arr is not None:
                    try:
                        n = max(1, int(arr.get("count", 1)))
                    except (TypeError, ValueError):
                        n = 1
                from_ids = (["%s#%d" % (pid, i) for i in range(n)]
                            if n > 1 else [pid])
                for rel in (part.get("relations") or []):
                    if not isinstance(rel, dict):
                        continue
                    if rel.get("this"):
                        froms = [rel.get("this")]
                    else:
                        froms = from_ids
                    for frm in froms:
                        e = dict(rel)
                        e["from"] = frm
                        raw.append(e)
    out = []
    for e in raw:
        if isinstance(e, dict) and e.get("type") in contact:
            out.append({
                "type": e.get("type"),
                "from": e.get("from"),
                "to": e.get("to"),
                "to2": e.get("to2"),
                "at_surface": e.get("at_surface"),
                "tol": e.get("tol"),
                "penetration": e.get("penetration"),
            })
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Emit a scoped idempotent STAGE preamble for "
                    "execute_rhinoscript_python_code.")
    parser.add_argument("--stage", required=True,
                        help="stage id; stamped as UserString 'stage' and used "
                             "as the delete scope.")
    parser.add_argument("--part-ids", default=None,
                        help="optional comma-separated part_id allow-list to "
                             "delete in addition to the stage tag.")
    parser.add_argument("--layer", default=None,
                        help="optional layer full path; whole-layer stage scope.")
    parser.add_argument("--connectivity-edges", default=None,
                        help="path to (or inline JSON of) THIS stage's declared "
                             "contact edges / a build-plan or scene-graph to lift "
                             "them from. When given, ALSO emit the §13/C9 "
                             "connectivity-sweep postamble (A1 realized gap by "
                             "GUID, A2 obb capture, A3 band, B1 violations-only).")
    parser.add_argument("--conn-tol", type=float, default=0.01,
                        help="acceptance tolerance (model units) used by the "
                             "emitted connectivity band check (default 0.01).")
    parser.add_argument("--conn-penetration", type=float, default=2.0,
                        help="default seating depth (model units) for "
                             "lands_on/meets/spans bands in the emitted sweep "
                             "(default 2.0).")
    parser.add_argument("--json-meta", action="store_true",
                        help="print {stage,scope} metadata to stderr for logging.")
    args = parser.parse_args(argv)

    part_ids = None
    if args.part_ids:
        part_ids = [p.strip() for p in args.part_ids.split(",") if p.strip()]

    snippet = render(args.stage, part_ids, args.layer)
    sys.stdout.write(snippet)

    edges = None
    if args.connectivity_edges:
        edges = _load_edges(args.connectivity_edges)
        # The sweep postamble is appended in the SAME execute_* call, AFTER the
        # caller's bake code -- here we emit it directly after the preamble so a
        # bake-free stage (pure connectivity re-check) is still a single snippet.
        sys.stdout.write(render_connectivity_sweep(
            edges, args.conn_tol, args.conn_penetration))

    if args.json_meta:
        sys.stderr.write(json.dumps({
            "stage": args.stage,
            "part_ids": part_ids,
            "layer": args.layer,
            "connectivity_edges": len(edges) if edges is not None else None,
        }) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
