#!/usr/bin/env python3
"""Emit the RhinoCommon preamble that makes a build STAGE scoped + idempotent.

Why this exists
---------------
The MCP execute_* wrappers were observed to run an emitted script TWICE (E1:
doubled stdout, 35 solids instead of 18). A whole-build "wipe everything and
rebuild" idempotency self-corrects the doubling but rebuilds ALL 931 solids to
fix one stage (E5/E10). This helper emits a *scoped* idempotent preamble: it
deletes ONLY the live objects whose UserString "stage" (or "part_id" prefix)
matches THIS stage, then the caller re-creates that stage's parts once. Running
the stage script twice therefore converges to exactly one copy of the stage,
and a failure in one stage never touches another stage's geometry.

It does NOT execute Rhino (no live Rhino/MCP here). It is a CODEGEN helper: it
prints a ready-to-run `#! python3` snippet to stdout that the modeling pipeline
hands to `execute_rhinoscript_python_code`. stdlib-only; 3.9-compatible; passes
`python3 -m py_compile`.

Usage
-----
    python3 stage_emit.py --stage bell_chamber
    python3 stage_emit.py --stage bell_chamber --part-ids bell_floor,bell_col_0,bell_col_1
    python3 stage_emit.py --stage bell_chamber --layer Pisa::BellChamber

The emitted snippet defines `purge_stage()` and runs it, then prints a JSON
line `{"stage": "...", "deleted": <n>}` so the caller knows the pre-state was
cleaned. The caller appends its guarded Create*/bake code AFTER this preamble,
inside the SAME execute_* call, so delete+rebuild is one atomic stage unit.
"""

import argparse
import json
import sys


# The emitted snippet. `{stage}`, `{part_ids_literal}`, `{layer_literal}` are
# filled in by render(). Everything the snippet needs is in scriptcontext.
_TEMPLATE = '''#! python3
# SCOPED IDEMPOTENT STAGE PREAMBLE -- generated by stage_emit.py
# Deletes only THIS stage's objects, then the caller re-creates them once.
# Safe to run twice (E1 double-execution self-corrects within the stage).
import scriptcontext as sc
import Rhino
import json

STAGE = {stage}
PART_IDS = {part_ids_literal}        # explicit allow-list, or None to match by stage tag
LAYER = {layer_literal}              # optional layer scope, or None

def _obj_in_stage(obj):
    """True if a live object belongs to THIS stage (delete target)."""
    a = obj.Attributes
    # 1. Strongest signal: a UserString "stage" stamped at bake time.
    if a.GetUserString("stage") == STAGE:
        return True
    # 2. Explicit part_id allow-list for this stage.
    if PART_IDS is not None:
        pid = a.GetUserString("part_id")
        if pid in PART_IDS:
            return True
    # 3. Layer scope (whole-layer stage). Compare resolved layer full path.
    if LAYER is not None:
        li = a.LayerIndex
        if 0 <= li < sc.doc.Layers.Count:
            if sc.doc.Layers[li].FullPath == LAYER:
                return True
    return False

def purge_stage():
    """Delete every live object that belongs to this stage. Returns count."""
    # Snapshot ids first; never mutate the table while enumerating it.
    doomed = [o.Id for o in sc.doc.Objects if _obj_in_stage(o)]
    n = 0
    for gid in doomed:
        if sc.doc.Objects.Delete(gid, True):   # quiet=True
            n += 1
    return n

_deleted = purge_stage()
# IMPORTANT for the create-then-find-newest shim: take the GUID snapshot for the
# newest-object diff AFTER the purge, so deleted objects never confuse the diff.
_stage_before_ids = set(o.Id for o in sc.doc.Objects)
print(json.dumps({{"stage": STAGE, "deleted": _deleted}}))
# ---- caller appends guarded Create* / bake code for this stage below ----
# Every bake in this stage MUST stamp the stage tag so a re-run can find it:
#     attr.SetUserString("stage", STAGE)
#     attr.SetUserString("part_id", part_id)
'''


def py_literal(value):
    """Render a Python literal for a str / list-of-str / None."""
    if value is None:
        return "None"
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, (list, tuple)):
        return "{" + ", ".join(repr(str(v)) for v in value) + "}"
    raise TypeError("unsupported literal: %r" % (value,))


def render(stage, part_ids, layer):
    """Return the ready-to-run stage preamble snippet as a string."""
    if not stage:
        raise ValueError("--stage is required and must be non-empty")
    return _TEMPLATE.format(
        stage=repr(str(stage)),
        part_ids_literal=py_literal(part_ids),
        layer_literal=py_literal(layer),
    )


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Emit a scoped idempotent STAGE preamble for "
                    "execute_rhinoscript_python_code.")
    parser.add_argument("--stage", required=True,
                        help="stage id; stamped as UserString 'stage' and used "
                             "as the delete scope.")
    parser.add_argument("--part-ids", default=None,
                        help="optional comma-separated part_id allow-list to "
                             "delete in addition to the stage tag.")
    parser.add_argument("--layer", default=None,
                        help="optional layer full path; whole-layer stage scope.")
    parser.add_argument("--json-meta", action="store_true",
                        help="print {stage,scope} metadata to stderr for logging.")
    args = parser.parse_args(argv)

    part_ids = None
    if args.part_ids:
        part_ids = [p.strip() for p in args.part_ids.split(",") if p.strip()]

    snippet = render(args.stage, part_ids, args.layer)
    sys.stdout.write(snippet)

    if args.json_meta:
        sys.stderr.write(json.dumps({
            "stage": args.stage,
            "part_ids": part_ids,
            "layer": args.layer,
        }) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
